server:
  servlet:
    context-path: /phaedra/query-service
  port: 8080

spring:
  application:
    name: phaedra-query-service
  jackson:
    serialization:
      indent_output: true
  cloud:
    kubernetes:
      enabled: true
  liquibase:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost
  graphql:
    graphiql:
      enabled: true


logging:
  file:
    name: /var/log/queryservice.log

